# Generated by Django 5.2.5 on 2025-08-21 06:40

import utils.validacoes.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=utils.validacoes.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
