# Generated by Django 5.2.3 on 2025-07-01 04:18

import django.db.models.deletion
import libs.uuid7
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.UUIDField(default=libs.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('codigo_aluno', models.CharField(default=students.models.gerar_codigo_aluno, help_text='Código único do aluno para identificação e QR Code', max_length=9, unique=True)),
                ('status', models.CharField(default='Pendente', help_text='Status do aluno (Ex: Pendente, Ativo, Inativo)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, help_text='CPF do dependente (opcional)', max_length=14, null=True, unique=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('escola_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('escola_serie_periodo', models.CharField(blank=True, help_text="Combinação de série e período, ex: '9º ano - Tarde'", max_length=100, null=True)),
                ('plano_saude_qual', models.CharField(blank=True, help_text='Nome do plano de saúde, se houver.', max_length=255, null=True)),
                ('alergias_quais', models.CharField(blank=True, help_text='Descrição das alergias, se houver.', max_length=255, null=True)),
                ('medicamentos_quais', models.CharField(blank=True, help_text='Nomes dos medicamentos em uso, se houver.', max_length=255, null=True)),
                ('condicoes_medicas', models.TextField(blank=True, help_text='Descrição de outras condições médicas gerais, se houver.', null=True)),
                ('contato_emergencia_nome', models.CharField(max_length=255)),
                ('contato_emergencia_telefone', models.CharField(max_length=20)),
                ('responsavel', models.ForeignKey(help_text='O responsável por este dependente', on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='users.responsavel')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEsportivo',
            fields=[
                ('id', models.UUIDField(default=libs.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('esporte', models.CharField(max_length=100)),
                ('faixa', models.CharField(max_length=100)),
                ('graduacao', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_esportivo', to='students.dependente')),
            ],
            options={
                'verbose_name': 'Histórico Esportivo',
                'verbose_name_plural': 'Históricos Esportivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermoAceite',
            fields=[
                ('id', models.UUIDField(default=libs.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nome_termo', models.CharField(help_text='Identificação do termo assinado (Ex: Termo de Uso de Imagem)', max_length=255)),
                ('pdf_gerado', models.FileField(help_text='Arquivo PDF com a assinatura eletrônica', upload_to='termos_assinados/')),
                ('ip_assinatura', models.GenericIPAddressField()),
                ('geolocalizacao', models.CharField(blank=True, help_text='Latitude e Longitude (opcional)', max_length=100, null=True)),
                ('data_aceite', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_aceitos', to='students.dependente')),
            ],
            options={
                'verbose_name': 'Termo de Aceite',
                'verbose_name_plural': 'Termos de Aceite',
                'ordering': ['-data_aceite'],
            },
        ),
    ]
