# Generated by Django 5.2.3 on 2025-07-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependente',
            name='escola_serie_periodo',
        ),
        migrations.AddField(
            model_name='dependente',
            name='escola_periodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dependente',
            name='escola_serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
