[project]
name = "uemura"
version = "0.1.0"
description = "Projeto Uemura inicializado do zero, gerenciado com uv."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
]

[tool.uv]
dev-dependencies = []


