[project]
name = "uemura"
version = "0.1.0"
description = "Projeto Uemura inicializado do zero, gerenciado com uv."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argon2-cffi>=25.1.0",
    "django>=5.2.5",
    "django-environ>=0.12.0",
]

[tool.uv]
dev-dependencies = []


