# Generated by Django 5.2.4 on 2025-08-20 06:25

import utils.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(verbose_name='Data da Aula')),
                ('data_entrada', models.DateTimeField(verbose_name='Data e Hora de Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Saída')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificado', 'Justificado'), ('atrasado', 'Atrasado')], default='presente', max_length=20, verbose_name='Status')),
                ('qr_code_utilizado', models.CharField(help_text='Código alfanumérico usado para o check-in/check-out', max_length=10, verbose_name='QR Code Utilizado')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a presença do atleta', verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'ordering': ['-data_aula', '-data_entrada', 'atleta__nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao', models.CharField(help_text='Ex: Faixa Preta 1º Dan, Faixa Marrom, etc.', max_length=50, verbose_name='Graduação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Professor Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['usuario__first_name', 'graduacao'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Turma A - Jiu-Jitsu Iniciante', max_length=100, verbose_name='Nome da Turma')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista dos dias da semana que a turma funciona', verbose_name='Dias da Semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('capacidade_maxima', models.PositiveIntegerField(default=20, help_text='Número máximo de alunos por turma', verbose_name='Capacidade Máxima')),
                ('ativa', models.BooleanField(default=True, verbose_name='Turma Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['modalidade__nome', 'nome', 'horario_inicio'],
            },
        ),
    ]
