# Generated by Django 5.2.4 on 2025-08-20 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frequencia', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='usuarios.atleta', verbose_name='Atleta'),
        ),
        migrations.AddField(
            model_name='professor',
            name='modalidades',
            field=models.ManyToManyField(help_text='Selecione as modalidades que este professor pode ensinar', to='usuarios.modalidade', verbose_name='Modalidades que ensina'),
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frequencia.professor', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.modalidade', verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frequencia.professor', verbose_name='Professor Responsável'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frequencia.turma', verbose_name='Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('modalidade', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together={('atleta', 'turma', 'data_aula')},
        ),
    ]
