# Generated by Django 5.2.4 on 2025-08-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependente',
            options={'ordering': ['usuario__first_name', 'data_nascimento'], 'verbose_name': 'Atleta', 'verbose_name_plural': 'Atletas'},
        ),
        migrations.AlterField(
            model_name='dependente',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do dependente (opcional)', null=True, upload_to='dependentes/fotos/', verbose_name='Foto'),
        ),
    ]
