# Generated by Django 5.2.4 on 2025-08-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dependente',
            constraint=models.UniqueConstraint(fields=('usuario', 'nome_completo', 'cpf'), name='unique_dependente_por_usuario'),
        ),
    ]
