# Generated by Django 5.2.4 on 2025-08-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20250820_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='qr_code_imagem',
            field=models.ImageField(blank=True, help_text='QR Code gerado automaticamente a partir do código do atleta', null=True, upload_to='atletas/qrcodes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_conta',
            field=models.CharField(choices=[('RESPONSAVEL', 'Responsável'), ('PROFESSOR', 'Professor'), ('GESTOR', 'Gestor'), ('FUNCIONARIO', 'Funcionário'), ('ADMIN', 'Administrador')], default='RESPONSAVEL', max_length=20, verbose_name='Tipo de Conta'),
        ),
    ]
