# Generated by Django 5.2.4 on 2025-08-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_dependente_unique_dependente_por_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Modalidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Modalidade Ativa')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='StatusMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Status')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#007bff', help_text='Código hexadecimal da cor (ex: #007bff)', max_length=7, verbose_name='Cor do Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Status Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Status de Matrícula',
                'verbose_name_plural': 'Status de Matrícula',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('gratuito', models.BooleanField(default=False, verbose_name='Matrícula Gratuita')),
                ('taxa_inscricao', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Taxa de Inscrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Tipo Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Tipo de Matrícula',
                'verbose_name_plural': 'Tipos de Matrícula',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='dependente',
            options={'ordering': ['usuario__first_name', 'data_nascimento'], 'verbose_name': 'Dependente', 'verbose_name_plural': 'Dependentes'},
        ),
        migrations.RemoveConstraint(
            model_name='dependente',
            name='unique_dependente_por_usuario',
        ),
        migrations.RemoveField(
            model_name='dependente',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='dependente',
            name='data_matricula',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Matrícula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_conta',
            field=models.CharField(choices=[('RESPONSAVEL', 'Responsável'), ('PROFESSOR', 'Professor'), ('GESTOR', 'Gestor'), ('FUNCIONARIO', 'Funcionário')], default='RESPONSAVEL', max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, help_text='Indica se o email foi verificado pelo usuário', verbose_name='Email Verificado'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='modalidade',
            field=models.ForeignKey(blank=True, help_text='Modalidade escolhida (apenas para matrícula paga)', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.modalidade', verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='status_matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.statusmatricula', verbose_name='Status da Matrícula'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='tipo_matricula',
            field=models.ForeignKey(blank=True, help_text='Projeto Social (gratuito) ou Modalidade Paga', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipomatricula', verbose_name='Tipo de Matrícula'),
        ),
        migrations.AddConstraint(
            model_name='dependente',
            constraint=models.UniqueConstraint(fields=('usuario', 'cpf'), name='unique_dependente_por_usuario'),
        ),
    ]
