# Generated by Django 5.2.4 on 2025-08-18 01:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_dependente_options_alter_dependente_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependente',
            name='data_matricula',
        ),
        migrations.RemoveField(
            model_name='dependente',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='dependente',
            name='status_matricula',
        ),
        migrations.RemoveField(
            model_name='dependente',
            name='tipo_matricula',
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(default=datetime.date.today, verbose_name='Data da Matrícula')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início das Aulas')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término das Aulas')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativa', models.BooleanField(default=True, verbose_name='Matrícula Ativa')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='usuarios.dependente', verbose_name='Atleta')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.modalidade', verbose_name='Modalidade')),
                ('status_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.statusmatricula', verbose_name='Status da Matrícula')),
                ('tipo_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipomatricula', verbose_name='Tipo de Matrícula')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-data_matricula', 'atleta__nome'],
                'unique_together': {('atleta', 'modalidade', 'ativa')},
            },
        ),
    ]
