# Generated by Django 5.2.4 on 2025-08-18 01:23

import utils.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_dependente_data_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='id',
            field=models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='id',
            field=models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusmatricula',
            name='id',
            field=models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipomatricula',
            name='id',
            field=models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
