# Generated by Django 5.2.4 on 2025-08-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_dependente_id_alter_matricula_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem representativa da modalidade (recomendado: 300x300px)', null=True, upload_to='modalidades/', verbose_name='Imagem da Modalidade'),
        ),
    ]
