# Generated by Django 5.2.3 on 2025-07-01 13:19

import libs.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextoTermo',
            fields=[
                ('id', models.UUIDField(default=libs.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('identificador', models.SlugField(help_text="Identificador único para a API (ex: 'responsabilidade')", unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField(help_text='Conteúdo do termo em formato Markdown')),
                ('versao', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Texto de Termo',
                'verbose_name_plural': 'Textos de Termos',
                'ordering': ['titulo'],
            },
        ),
    ]
