# Generated by Django 5.2.4 on 2025-08-18 04:07

import utils.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('nome_empresarial', models.CharField(max_length=200, verbose_name='Nome Empresarial')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone1', models.CharField(max_length=15, verbose_name='Telefone 1')),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2')),
                ('situacao_cadastral', models.CharField(max_length=50, verbose_name='Situação Cadastral')),
                ('horarios_atendimento', models.TextField(verbose_name='Horários de Atendimento')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('id', models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome_fantasia'],
            },
        ),
    ]
