# Generated by Django 5.2.4 on 2025-08-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='domingo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='quarta_feira',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quarta-feira'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='quinta_feira',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quinta-feira'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sabado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sábado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='segunda_feira',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segunda-feira'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sexta_feira',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexta-feira'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='terca_feira',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Terça-feira'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='horarios_atendimento',
            field=models.TextField(blank=True, null=True, verbose_name='Horários Gerais'),
        ),
    ]
