# Generated by Django 5.2.4 on 2025-08-19 04:14

import utils.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_domingo_empresa_quarta_feira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('assunto', models.CharField(choices=[('matricula', 'Matrícula'), ('projeto_social', 'Projeto Social'), ('horarios', 'Horários'), ('precos', 'Preços'), ('outro', 'Outro')], max_length=50, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('id', models.UUIDField(default=utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('lida', models.BooleanField(default=False, verbose_name='Mensagem Lida')),
                ('respondida', models.BooleanField(default=False, verbose_name='Respondida')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-data_envio'],
            },
        ),
    ]
