# Generated by Django 5.2.4 on 2025-08-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_mensagemcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermosCondicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('responsabilidade', 'Termos de Responsabilidade'), ('medicas', 'Termos de Condições Médicas'), ('imagem', 'Direito de Uso de Imagem')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(help_text='Use {{NOME_EMPRESA}}, {{DATA_ATUAL}}, {{RESPONSAVEL}} como variáveis')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termos e Condições',
                'verbose_name_plural': 'Termos e Condições',
                'ordering': ['tipo'],
            },
        ),
    ]
