# Generated by Django 5.2.3 on 2025-07-01 04:18

import django.core.validators
import libs.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.UUIDField(default=libs.uuid7.uuid7, editable=False, help_text='ID único no formato UUIDv7', primary_key=True, serialize=False)),
                ('status', models.CharField(default='Ativo', help_text='Status do cadastro do responsável (Ex: Ativo, Inativo)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(help_text='CPF no formato 123.456.789-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('rg', models.CharField(blank=True, help_text='RG (opcional)', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(help_text='Telefone no formato (11) 98765-4321', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (11) 91234-5678', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')])),
                ('cep', models.CharField(help_text='CEP no formato 12345-678', max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Sigla do estado (Ex: SP)', max_length=2)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['nome_completo'],
            },
        ),
    ]
